class_name BalanceTable
extends Resource

@export var stat_multipliers: Array[float] = [1.00, 1.35, 1.82, 2.46, 3.32, 4.48, 6.05, 8.17]
@export var level_caps: Array[int] = [10, 20, 30, 40, 50, 60, 70, 80]
@export var equipment_affix_counts: Array[int] = [1, 1, 2, 2, 3, 3, 4, 4]
@export var core_socket_counts: Array[int] = [0, 0, 0, 0, 1, 1, 2, 2]
@export var essence_bases: Array[int] = [10, 25, 65, 165, 420, 1050, 2600, 6500]
@export var rank_up_essence_costs: Array[int] = [40, 110, 300, 800, 2200, 6000, 16000]
@export var resonance_trait_thresholds: Array[int] = [1, 3, 6]
@export var summon_weights: Array[int] = [4000, 2700, 1700, 1000, 450, 120, 28, 2]
@export var summon_pull_cost: int = 100
@export var xp_coefficient: int = 10
@export var xp_per_wave: int = 4
@export var arena_move_speed: float = 5.8
@export var arena_sprint_speed: float = 8.0
@export var arena_acceleration: float = 42.0
@export var arena_deceleration: float = 65.0
@export var arena_turn_speed_degrees: float = 1200.0
@export var arena_mouse_sensitivity: float = 0.003
@export var arena_camera_spring_length: float = 4.0
@export var arena_camera_pitch_up_degrees: float = 35.0
@export var arena_camera_pitch_down_degrees: float = 65.0
@export var arena_light_attack_startup: float = 0.12
@export var arena_light_attack_active: float = 0.10
@export var arena_light_attack_recovery: float = 0.22
@export var arena_light_attack_displacement: float = 2.0
@export var arena_light_attack_reach: float = 1.5
@export var arena_light_attack_hit_stop: float = 0.04
@export var arena_enemy_attack_startup: float = 0.55
@export var arena_enemy_attack_active: float = 0.10
@export var arena_enemy_attack_recovery: float = 0.45
@export var arena_enemy_attack_reach: float = 1.6
@export var arena_enemy_attack_trigger_range: float = 3.0
@export var arena_enemy_attack_cooldown: float = 0.6
@export var arena_enemy_turn_speed_degrees: float = 720.0
@export var arena_enemy_attack_hit_stop: float = 0.06
@export var arena_enemy_knockback_speed: float = 6.0
@export var arena_enemy_hit_stun: float = 0.35
@export var arena_enemy_hits_to_kill_hero: int = 3
@export var arena_result_return_delay: float = 1.0
@export var arena_dodge_speed: float = 13.5
@export var arena_dodge_duration: float = 0.38
@export var arena_dodge_iframe_duration: float = 0.25
@export var arena_dodge_cooldown: float = 0.15
@export var arena_parry_startup: float = 0.0
@export var arena_parry_active_window: float = 0.18
@export var arena_parry_whiff_recovery: float = 0.35
@export var arena_parry_success_recovery: float = 0.10
@export var arena_parry_cooldown: float = 0.15
@export var arena_parry_hit_stop: float = 0.08
@export var arena_parry_enemy_stagger: float = 0.6
@export var rank_names: PackedStringArray = ["F", "D", "C", "B", "A", "S", "SS", "SSS"]
@export var equip_pct_per_rank: Array[float] = [0.04, 0.054, 0.0728, 0.0984, 0.1328, 0.1792, 0.242, 0.3268]
@export var equip_crit_pct_per_rank: Array[float] = [0.015, 0.02025, 0.0273, 0.0369, 0.0498, 0.0672, 0.09075, 0.12255]
@export var equip_crit_rate_cap: float = 0.75
@export var enhance_pct_per_level: float = 0.08

@export var summoning_circle_multiplier_per_level: float = 0.15
@export var wave_damage_coefficient: float = 0.35
@export var wave_loss_damage_coefficient: float = 1.0
@export var summoning_circle_level_cap: int = 5
@export var forge_enhance_cap_per_level: int = 3
@export var forge_enhance_cap_max: int = 15
@export var forge_salvage_yield_bonus: float = 0.10
@export var training_hall_xp_bonus: float = 0.15
@export var sanctum_essence_yield_bonus: float = 0.10
@export var reliquary_decay_turns_bonus: int = 5
@export var reliquary_damage_chance_reduction: float = 0.03
